# This workflow will do a clean installation of node dependencies, cache/restore them, and run tests

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
permissions:
  contents: read
jobs:
  build:
    name: Typecheck, test, and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Enable corepack
        run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Typecheck
        run: yarn typecheck
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
