name: Deploy to NPM

on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
