name: Deploy to NPM

on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  id-token: write  # Required for OIDC
  contents: read
jobs:
  build-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - run: yarn install --immutable
      - run: yarn build --if-present
      - run: yarn test
      - run: npm publish  # Or: npm stage publish
